import itertools
import string
import hashlib

def load_hashfile(filepath):
    """Load hash values from a file generated by hcxpcapngtool."""
    with open(filepath, 'r') as file:
        return [line.strip() for line in file]

def hash_function(word):
    """Hash function using SHA-1 for WPA/WPA2 PSK (commonly used in WiFi)."""
    return hashlib.sha1(word.encode()).hexdigest()

def brute_force_hash_cracker(hash_list):
    characters = string.ascii_letters + string.digits + string.punctuation
    length = 8

    for combination in itertools.product(characters, repeat=length):
        word = ''.join(combination)
        hashed_word = hash_function(word)
        if hashed_word in hash_list:
            print(f"Match found: {word}")
            return word
    print("No match found.")
    return None

if __name__ == "__main__":
    # Load hash values from the file generated by hcxpcapngtool
    hash_list = load_hashfile('hashfile.txt')

    # Perform brute-force attack
    brute_force_hash_cracker(hash_list)